.DEFAULT_GOAL : all
all : build
build:
	gcc main.c -o program
clean:
	rm -f program
run:
	./program
test:
	./program 1
	./program 2 3
	./program 4 5 6 
	./program 7 8 9 10
	./program 11 12 13 14 15
	./program 16